version: "3"

volumes:
  database:

networks:
  frontend:
  backend:

services:
  db:
    container_name: db
    image: mongo
    restart: always
    environment: 
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - ../db/dist/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - database:/data/db
    networks:
      - backend

  api:
    container_name: api
    image: node
    restart: always
    working_dir: /app
    depends_on:
      - db
    volumes: 
      - ../api:/app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    command: npm run dev
    networks:
      - frontend
      - backend

  frontend:
    container_name: frontend
    image: node
    restart: always
    working_dir: /app
    depends_on:
      - api
    volumes: 
      - ../frontend:/app
    command: npm run dev
    ports: 
      - 80:3000
    networks:
      - frontend